import os
import re
from pathlib import Path


MODEL_NAME = os.getenv("STOREPILOT_EMBEDDING_MODEL", "BAAI/bge-m3")
EMBEDDING_PROVIDER = os.getenv("STOREPILOT_EMBEDDING_PROVIDER", "local").strip().lower()
EMBEDDING_DEVICE = os.getenv("STOREPILOT_EMBEDDING_DEVICE", "auto").strip().lower()
EMBEDDING_BATCH_SIZE = int(os.getenv("STOREPILOT_EMBEDDING_BATCH_SIZE", "32"))
EMBEDDING_USE_FP16 = os.getenv("STOREPILOT_EMBEDDING_USE_FP16", "true").strip().lower() in {"1", "true", "yes"}
EMBEDDING_API_KEY = os.getenv("STOREPILOT_EMBEDDING_API_KEY", "")
EMBEDDING_API_BASE_URL = os.getenv("STOREPILOT_EMBEDDING_API_BASE_URL", "https://api.openai.com/v1").rstrip("/")
EMBEDDING_API_MODEL = os.getenv("STOREPILOT_EMBEDDING_API_MODEL", "text-embedding-3-small")
EMBEDDING_API_DIMENSIONS = int(os.getenv("STOREPILOT_EMBEDDING_API_DIMENSIONS", "1536"))
EMBEDDING_API_TIMEOUT_SECONDS = float(os.getenv("STOREPILOT_EMBEDDING_API_TIMEOUT_SECONDS", "60"))
EMBEDDING_API_BATCH_SIZE = int(os.getenv("STOREPILOT_EMBEDDING_API_BATCH_SIZE", "100"))
CACHE_ROOT = Path(os.getenv("STOREPILOT_AI_CACHE_ROOT", "ai-cache/categories"))
MODEL_CACHE_KEY = re.sub(r"[^A-Za-z0-9_.-]+", "_", MODEL_NAME).strip("_").lower()
CATEGORY_EMBEDDING_SEARCH_K = int(os.getenv("STOREPILOT_CATEGORY_EMBEDDING_SEARCH_K", "15"))
CATEGORY_EMBEDDING_CANDIDATE_K = int(os.getenv("STOREPILOT_CATEGORY_EMBEDDING_CANDIDATE_K", "5"))

LLM_API_KEY = os.getenv("STOREPILOT_LLM_API_KEY", "")
LLM_BASE_URL = os.getenv("STOREPILOT_LLM_BASE_URL", "https://api.openai.com/v1").rstrip("/")
LLM_MODEL = os.getenv("STOREPILOT_LLM_MODEL", "gpt-4o-mini")
LLM_TIMEOUT_SECONDS = float(os.getenv("STOREPILOT_LLM_TIMEOUT_SECONDS", "90"))
LLM_BATCH_SIZE = int(os.getenv("STOREPILOT_LLM_BATCH_SIZE", "15"))
LLM_MAX_CONCURRENCY = int(os.getenv("STOREPILOT_LLM_MAX_CONCURRENCY", "20"))

PRODUCT_CACHE_ROOT = Path(os.getenv("STOREPILOT_PRODUCT_CACHE_ROOT", "ai-cache/products"))
PRODUCT_SEARCH_K = int(os.getenv("STOREPILOT_PRODUCT_SEARCH_K", "20"))
PRODUCT_INDEX_TYPE = os.getenv("STOREPILOT_PRODUCT_INDEX_TYPE", "flat").strip().lower()
PRODUCT_HNSW_M = int(os.getenv("STOREPILOT_PRODUCT_HNSW_M", "32"))
PRODUCT_HNSW_EF_CONSTRUCTION = int(os.getenv("STOREPILOT_PRODUCT_HNSW_EF_CONSTRUCTION", "200"))
PRODUCT_HNSW_EF_SEARCH = int(os.getenv("STOREPILOT_PRODUCT_HNSW_EF_SEARCH", "64"))
PRODUCT_REPRESENTATIVE_K = int(os.getenv("STOREPILOT_PRODUCT_REPRESENTATIVE_K", "5"))
PRODUCT_DUPLICATE_THRESHOLD = float(os.getenv("STOREPILOT_PRODUCT_DUPLICATE_THRESHOLD", "0.985"))
PRODUCT_DISTRIBUTION_TEMPERATURE = float(os.getenv("STOREPILOT_PRODUCT_DISTRIBUTION_TEMPERATURE", "0.05"))

AUTO_ACCEPT_THRESHOLD = float(os.getenv("STOREPILOT_AUTO_ACCEPT_THRESHOLD", "0.90"))
LLM_THRESHOLD = float(os.getenv("STOREPILOT_LLM_THRESHOLD", "0.85"))
CATEGORY_SUPPORT_THRESHOLD = float(os.getenv("STOREPILOT_CATEGORY_SUPPORT_THRESHOLD", "0.75"))
CATEGORY_MARGIN_THRESHOLD = float(os.getenv("STOREPILOT_CATEGORY_MARGIN_THRESHOLD", "0.15"))
AUTO_ACCEPT_MIN_EXAMPLES = int(os.getenv("STOREPILOT_AUTO_ACCEPT_MIN_EXAMPLES", "3"))
