import os
import re
from pathlib import Path


MODEL_NAME = os.getenv("STOREPILOT_EMBEDDING_MODEL", "BAAI/bge-m3")
EMBEDDING_DEVICE = os.getenv("STOREPILOT_EMBEDDING_DEVICE", "auto").strip().lower()
EMBEDDING_BATCH_SIZE = int(os.getenv("STOREPILOT_EMBEDDING_BATCH_SIZE", "32"))
EMBEDDING_USE_FP16 = os.getenv("STOREPILOT_EMBEDDING_USE_FP16", "true").strip().lower() in {"1", "true", "yes"}
CACHE_ROOT = Path(os.getenv("STOREPILOT_AI_CACHE_ROOT", "ai-cache/categories"))
MODEL_CACHE_KEY = re.sub(r"[^A-Za-z0-9_.-]+", "_", MODEL_NAME).strip("_").lower()

GUNPLA_CATEGORY_BONUS = float(os.getenv("STOREPILOT_GUNPLA_CATEGORY_BONUS", "0.3"))
BODY_KEYWORD_CATEGORY_BONUS = float(os.getenv("STOREPILOT_BODY_KEYWORD_CATEGORY_BONUS", "0.25"))
BODY_KEYWORD_EXACT_CATEGORY_BONUS = float(os.getenv("STOREPILOT_BODY_KEYWORD_EXACT_CATEGORY_BONUS", "0.15"))
BODY_KEYWORD_NON_MATCH_PENALTY = float(os.getenv("STOREPILOT_BODY_KEYWORD_NON_MATCH_PENALTY", "0.35"))

LLM_API_KEY = os.getenv("STOREPILOT_LLM_API_KEY", "")
LLM_BASE_URL = os.getenv("STOREPILOT_LLM_BASE_URL", "https://api.openai.com/v1").rstrip("/")
LLM_MODEL = os.getenv("STOREPILOT_LLM_MODEL", "gpt-4o-mini")
LLM_TIMEOUT_SECONDS = float(os.getenv("STOREPILOT_LLM_TIMEOUT_SECONDS", "90"))
LLM_BATCH_SIZE = int(os.getenv("STOREPILOT_LLM_BATCH_SIZE", "30"))

PRODUCT_CACHE_ROOT = Path(os.getenv("STOREPILOT_PRODUCT_CACHE_ROOT", "ai-cache/products"))
PRODUCT_SEARCH_K = int(os.getenv("STOREPILOT_PRODUCT_SEARCH_K", "20"))
PRODUCT_INDEX_TYPE = os.getenv("STOREPILOT_PRODUCT_INDEX_TYPE", "flat").strip().lower()
PRODUCT_HNSW_M = int(os.getenv("STOREPILOT_PRODUCT_HNSW_M", "32"))
PRODUCT_HNSW_EF_CONSTRUCTION = int(os.getenv("STOREPILOT_PRODUCT_HNSW_EF_CONSTRUCTION", "200"))
PRODUCT_HNSW_EF_SEARCH = int(os.getenv("STOREPILOT_PRODUCT_HNSW_EF_SEARCH", "64"))
PRODUCT_REPRESENTATIVE_K = int(os.getenv("STOREPILOT_PRODUCT_REPRESENTATIVE_K", "5"))
PRODUCT_MAX_PER_CATEGORY = int(os.getenv("STOREPILOT_PRODUCT_MAX_PER_CATEGORY", "2"))
PRODUCT_DUPLICATE_THRESHOLD = float(os.getenv("STOREPILOT_PRODUCT_DUPLICATE_THRESHOLD", "0.985"))
PRODUCT_DISTRIBUTION_TEMPERATURE = float(os.getenv("STOREPILOT_PRODUCT_DISTRIBUTION_TEMPERATURE", "0.05"))

AUTO_ACCEPT_THRESHOLD = float(os.getenv("STOREPILOT_AUTO_ACCEPT_THRESHOLD", "0.95"))
LLM_THRESHOLD = float(os.getenv("STOREPILOT_LLM_THRESHOLD", "0.85"))
CATEGORY_SUPPORT_THRESHOLD = float(os.getenv("STOREPILOT_CATEGORY_SUPPORT_THRESHOLD", "0.75"))
CATEGORY_MARGIN_THRESHOLD = float(os.getenv("STOREPILOT_CATEGORY_MARGIN_THRESHOLD", "0.15"))
AUTO_ACCEPT_MIN_EXAMPLES = int(os.getenv("STOREPILOT_AUTO_ACCEPT_MIN_EXAMPLES", "3"))
